#!bin/bash

echo "Deseja instalar o BadVPN? [s / CTRL + C para abortar a instalação]"
read resposta

#Caso a resposta for s
if [ "$resposta" = "s" ]
then
clear
wget https://raw.githubusercontent.com/SrdasEstrelas/Conf.sh/master/badvpnconf.sh
mv badvpnconf.sh /bin
chmod 777 /bin/badvpnconf.sh
clear
bash /bin/badvpnconf.sh
fi
sleep 4
bash menu
