#!/bin/bash
clear

echo "----------------------------------"
echo " | Script by: Sr. das Estrelas |"
echo "----------------------------------"
echo ""
echo "
"[1] Configurar VPS SSH e Squid [Faça primeiro para liberar os demais comandos]"
"[2] Adicionar Usuario"
"[3] Deletar Usuario"
"[4] Monitorar Conexões"
"[5] Configurar OpenVPN"
"
echo "Escolha um numero para o seu respectivo comando"
read resposta

#Caso a resposta for 1
if [ "$resposta" = "1" ]
then
clear
wget https://raw.githubusercontent.com/SrdasEstrelas/Conf.sh/master/.configvps
mv .configvps /bin
chmod 777 /bin/.configvps
.configvps

fi

#Caso a resposta seja 2
if [ "$resposta" = "2" ]
then
clear
bash /bin/.Adduser
fi

#Caso a resposta seja 3
if [ "$resposta" = "3" ]
then
clear
bash /bin/.Deluser
fi

#Caso a resposta seja 4
if [ "$resposta" = "4" ]
then
clear
bash /bin/.Limiter
fi


#Caso a resposta seja 5
if [ "$resposta" = "5" ]
then
clear
bash /bin/.OpenVPN
fi

#Caso a resposta seja 6
if [ "$resposta" = "6" ]
then
clear
bash /bin/.BadUDP
fi
