#!/bin/bash
clear

#Adicionar Scripts na VPS
wget https://raw.githubusercontent.com/SrdasEstrelas/Conf.sh/master/.AlterarLimite
wget https://raw.githubusercontent.com/SrdasEstrelas/Conf.sh/master/.Adduser
wget https://raw.githubusercontent.com/SrdasEstrelas/Conf.sh/master/.BadVpn
wget https://raw.githubusercontent.com/SrdasEstrelas/Conf.sh/master/.Deluser
wget https://raw.githubusercontent.com/SrdasEstrelas/Conf.sh/master/limiter
wget https://raw.githubusercontent.com/SrdasEstrelas/Conf.sh/master/.OpenVPN
wget https://raw.githubusercontent.com/SrdasEstrelas/Conf.sh/master/monitor

mv .AlterarLimite /bin
mv .Adduser /bin
mv .BadVpn /bin
mv .Deluser /bin
mv limiter /bin
mv .OpenVPN /bin
mv monitor /bin
mv menu /bin

chmod -R 777 /bin/.AlterarLimite
chmod -R 777 /bin/.Adduser
chmod -R 777 /bin/.BadVpn
chmod -R 777 /bin/.Deluser
chmod -R 777 /bin/limiter
chmod -R 777 /bin/.OpenVPN
chmod -R 777 /bin/menu
chmod -R 777 /bin/monitor

clear

echo "----------------------------------"
echo " | Script by: Sr. das Estrelas |"
echo "----------------------------------"
echo ""
echo "
"[1] Configurar VPS SSH e Squid"
"[2] Adicionar Usuario"
"[3] Deletar Usuario"
"[4] Monitorar Conexões"
"[5] Configurar OpenVPN"
"[6] Configurar UDP _BadVPN"
"
echo "Escolha um numero para o seu respectivo comando"
read resposta

#Caso a resposta for 1
if [ "$resposta" = "1" ]
then
clear
wget https://raw.githubusercontent.com/SrdasEstrelas/Conf.sh/master/.configvps
mv .configvps /bin
chmod 777 /bin/.configvps
.configvps

fi

#Caso a resposta seja 2
if [ "$resposta" = "2" ]
then
clear
bash /bin/.Adduser
fi

#Caso a resposta seja 3
if [ "$resposta" = "3" ]
then
clear
bash /bin/.Deluser
fi

#Caso a resposta seja 4
if [ "$resposta" = "4" ]
then
clear
bash /bin/monitor
fi


#Caso a resposta seja 5
if [ "$resposta" = "5" ]
then
clear
bash /bin/.OpenVPN
fi

#Caso a resposta seja 6
if [ "$resposta" = "6" ]
then
clear
bash /bin/.BadVpn
fi
